### ISSUE TITLE
Create a real cache layer

### ISSUE THREAD

**Issue by JesusValera** [gacela-project/gacela#119]
## 📚  Description

Every time a request is sent to an application which runs Gacela, the framework should be bootstrapped.
We have already a cache layer in order to resolve the classes automatically if they were resolved in the same request, but once the request is over, if the user request the same endpoint, the framework should be bootstrapped and resolve the same classes over and over again.

My suggestion is to create a physical file where we save the information of the auto-resolved classes, so, even in different bootstrapping, if a class was already resolved in the past, it should not be resolved again.

## 💡 Suggestion

- Create a file (or multiple files, we should think about that) in the root and/or in `var` folder (maybe this configuration should be editable in the `config`.
- Enable a flag to create or not this cache file, can be `true` by default?
- Create a new command for resetting/removing the cache file/folder

**Comment by Chemaclass** [comment]
Closed: https://github.com/gacela-project/gacela/pull/120
Merged: https://github.com/gacela-project/gacela/pull/121
