### ISSUE TITLE
Remove deprecated FacadeResolverAwareTrait

### ISSUE THREAD

**Issue by Chemaclass** [gacela-project/gacela#152]
## 🔖  Description

The `FacadeResolverAwareTrait` was deprecated in favor of `DocBlockResolverAwareTrait`. This issue is about to remove the `FacadeResolverAwareTrait` and the tests that we have `GacelaTest\Feature\Framework\FacadeAware`.

**Comment by Anas-debug** [comment]
I'll take the issue.

**Comment by JesusValera** [comment]
I spot some problems with Laravel framework.

The controllers override the `_call()` method and there is a collision between the trait `DocBlockResolverAwareTrait` and the Laravel controller classes that extends from the `Controller` class.

Maybe we should allow both ways. What do you think? 🤔

**Comment by JesusValera** [comment]
I found a way to make it compatible with the current Laravel version, so, I removed the class completely 😄
